### ISSUE TITLE
invalide date

### ISSUE THREAD

**Issue by TonyStark** [pryv/rec-la#6]
trying `https://ss.rec.la` it gives `ERR_CERT_DATE_INVALID` error

i think certificate is expired.

**Comment by sgoumaz** [comment]
Hi @TonyStark, could you post the steps to reproduce the error? The [certificate](https://www.rec.la/rec.la-cert.crt) is up-to-date as far as I can see.

**Comment by TonyStark** [comment]
problem solved.
actually i was using old certificate. but now i updated from site and everything works
